### ISSUE TITLE
Add support for templating languages like _.template() ,mustache etc 

### ISSUE THREAD

**Issue by patrykwegrzyn** [mrhanlon/less-than-slash#20]
Here is small example of underscore template that results in 
```
<span>
    <%=obj.property %>
</%=obj.property %>
```
should be 
```
<span>
    <%=obj.property%>
</span>
```

**Comment by mrhanlon** [comment]
This should be easy to do with the new customizable parsers and a no-op handler.

**Comment by mrhanlon** [comment]
Since there is a proliferation of template tags like this, and furthermore they are customizable, we investigate creating a new setting for handling situations like this. I think if we refactored `parsers` and the corresponding handlers to a setting that took tag patterns to look for (and whether they are closing or not) then we can open this up to user-configuration.
