### ISSUE TITLE
Integrate with Autocomplete Plus package

### ISSUE THREAD

**Issue by brendanfalkowski** [mrhanlon/less-than-slash#7]
Reference: https://github.com/atom/atom/issues/4364#issuecomment-78358661

Was hoping this behavior might make its way into Autocomplete Plus, which is slated to become a core package. Was suggested this may become a provider for autocompletion.

Things whooshing over my head, but figured I'd suggest here. I'd love to see this be a core behavior in Atom (went two months missing it before I realized there was probably a package for it).

**Comment by mrhanlon** [comment]
Sounds like a good idea. I'll take a look at how Autocomplete Plus providers work. I'm not sure I'd want it to require that, but if there is a way to either make it do both or fork the project for the provider functionality.

**Comment by mrhanlon** [comment]
I wonder if the new [Services API](http://blog.atom.io/2015/03/25/new-services-API.html) would be the right way to integration this plugin with Autocomplete Plus.

**Comment by MarcoThePoro** [comment]
I just checked out the [Autocomplete+ Provider API](https://github.com/atom/autocomplete-plus/wiki/Provider-API).

It would be pretty easy to port the logic into an autocomplete provider but it would add an extra step to the completion flow since you would have to select the suggestion after typing `</` rather than it appearing immediately. 

This allows the user to ignore unwanted completions. But then again, less-than-slash is intelligent enough to know the correct completion every time.

I reckon we should add this as a different 'mode' in less-than-slash.

**Comment by MarcoThePoro** [comment]
Done in https://github.com/mrhanlon/less-than-slash/pull/24
